# Generated by Django 4.0.2 on 2022-02-19 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefone', models.IntegerField()),
                ('estado', models.CharField(max_length=200)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='especialidad',
            name='hostpital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.hospital'),
        ),
    ]
