# Generated by Django 4.0.2 on 2022-02-19 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulta.cita')),
            ],
        ),
    ]
