# Generated by Django 4.0.2 on 2022-02-16 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamenPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateField(null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('resultado', models.CharField(max_length=200)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultado.examen')),
                ('id_paciente', models.ManyToManyField(to='consulta.Paciente')),
            ],
        ),
    ]
