# Generated by Django 4.0.2 on 2022-02-19 02:13

import ast
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('cedula', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SintomasPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('discapacidad', models.BooleanField(default=False)),
                ('tipoDescapacidad', models.CharField(max_length=200)),
                ('grupSanguineo', models.CharField(max_length=200)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=200)),
                ('id_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entidad.medico')),
                ('id_paciente', models.ForeignKey(on_delete=ast.Delete, to='consulta.paciente')),
            ],
        ),
    ]
