# Generated by Django 4.0.2 on 2022-02-24 21:11

import ast
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0002_alter_especialidad_especialidad_and_more'),
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(max_length=200, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entidad.medico', verbose_name='Medico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=ast.Delete, to='consulta.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='turno',
            field=models.IntegerField(verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.IntegerField(verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='sintomaspaciente',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='sintomaspaciente',
            name='discapacidad',
            field=models.BooleanField(default=False, verbose_name='Discapcidad'),
        ),
        migrations.AlterField(
            model_name='sintomaspaciente',
            name='grupSanguineo',
            field=models.CharField(max_length=200, verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='sintomaspaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulta.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='sintomaspaciente',
            name='sintomas',
            field=models.CharField(max_length=200, verbose_name='Sintomas'),
        ),
        migrations.AlterField(
            model_name='sintomaspaciente',
            name='tipoDescapacidad',
            field=models.CharField(max_length=200, verbose_name='tipo de discapacidad'),
        ),
    ]
